#!/usr/bin/env node

import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const distDir = path.join(rootDir, "dist");
const outFile = path.join(distDir, "github-runner.min.js");

const banner = [
  "#!/usr/bin/env node",
  "/* Generated by xframe/github/scripts/build.js — do not edit. */",
].join("\n");

await esbuild.build({
  entryPoints: [path.join(rootDir, "src/cli.js")],
  outfile: outFile,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  minify: true,
  sourcemap: true,
  sourcesContent: true,
  legalComments: "none",
  banner: { js: banner },
  external: ["node:*"],
});

await fs.promises.chmod(outFile, 0o755);

console.log(`Wrote ${path.relative(rootDir, outFile)}`);
